name: NaviaChat
main: com.landsofnavia.naviachat.NaviaChat
version: Alpha 0.1.0
commands:
  ch:
    description: Used for changing channels.
    aliases: [cha, change]
    usage: |
        Invalid use of /<command>. Examples:
           /<command> g - Joins, and changes your focused channel, to the shortcutted channel 'g'.
  leavechannel:
    description: Used for leaving channels
    aliases: [lch]
    usage: |
        Invalid use of /<command>. Examples:
           /<command> g = Leaves the shortcutted channel 'g'
  channel:
    description: Used for managing channels.
    usage: |
        Invalid use. Examples:
           /<command> list - Lists channels.
           /<command> ban [Player] - Bans a player from current channel.
  t:
    description: Used for messaging.
    usage: /t <Player> <Message>
    aliases: [pm, message]
  me:
    description: Used for making emotes.
    usage: /me <Action>
  prefix:
    description: Used for prefixing.
    usage: /prefix <prefix|prefixgroup> <player|group> <prefix>
  dac:
    description: Used for managing the plugin.
    usage: /dac <Args...>
  ignore:
    description: Ignoring players.  
    usage: /ignore <Player>
permissions:
    naviachat.*:
        description: 'Gives access to everything naviachat related.'
        children:
            naviachat.channel.*: true
            naviachat.leavechannel: true
            naviachat.cantalk: true
            naviachat.tell: true
            naviachat.me: true
            naviachat.changechannel: true
        default: op
    naviachat.moderator:
        description: 'Gives access to moderator features.'
        children:
            naviachat.channel.ban: true
            naviachat.channel.unban: true
            naviachat.channel.mute: true
            naviachat.channel.unmute: true
        default: false
    naviachat.channel.*:
        description: 'Gives access to everything in the /channel command.'
        children:
            naviachat.channel.ban: true
            naviachat.channel.unban: true
            naviachat.channel.list.*: true
            naviachat.channel.mute: true
            naviachat.channel.unmute: true
        default: false
    naviachat.channel.list.*:
        description: 'Gives access to both channel lists.'
        children:
            naviachat.channel.list.in: true
            naviachat.channel.list.available: true
        default: false
    naviachat.basic:
        description: 'Everything you need for the regular chatter!'
        children:
            naviachat.leavechannel: true
            naviachat.channel.list.*: true
            naviachat.cantalk: true
            naviachat.tell: true
            naviachat.me: true
            naviachat.changechannel: true
        default: true
    naviachat.channel.ban:
        description: 'Gives the ability to ban players. Will elaborate soon.'
        default: false
    naviachat.channel.unban:
        description: 'Gives the ability to unban players. Will elaborate soon.'
        default: false
    naviachat.channel.list.in:
        description: 'Lists channels that the player is currently in.'
        default: false
    naviachat.channel.list.available:
        description: 'Lists channels available to the player.'
        default: false
    naviachat.cantalk:
        description: 'Gives the ability to talk. Will be channel-specific soon.'
        default: false
    naviachat.tell:
        description: 'Gives the ability to /t if enabled. NOT WORKING ATM.'
        default: false
    naviachat.me:
        description: 'Gives the ability to emote. Will be channel-specific soon. NOT WORKING ATM.'
        default: false
    naviachat.leavechannel:
        description: 'I do not think this node will ever be needed as an individual node, until I make it channel-specific. It just gives players access to leave channels for now.'
        default: false
    naviachat.changechannel:
        description: 'I do not think this node will ever be needed as an individual node either, until I make it channel-specific. It just gives players access to change channels for now.'
        default: false
    naviachat.channel.write.*:
        description: 'Gives permission to print the log of all channels.'
        default: op
    naviachat.prefix:
        description: 'Gives permission to set prefixes.'
        default: op
    naviachat.channel.mute:
        description: 'Gives permission to mute..'
        default: op
    naviachat.channel.unmute:
        description: 'Gives permission to unmute.'
        default: op
    naviachat.ignore:
        description: 'Gives permission to ignore.'
        default: true
